import { Movie, Series } from './types';

export const CURATED_MOVIES: Movie[] = [
  {
    id: 27205,
    title: 'Inception',
    slug: 'inception',
    overview:
      'Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets, is offered a chance to regain his old life as payment for a task considered to be impossible: "inception", the implantation of another person\'s idea into a target\'s subconscious.',
    posterPath: 'https://image.tmdb.org/t/p/w500/ljsZTbVsrQSqZgWeep2B1QiDKuh.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/w1280/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg',
    releaseDate: '2010-07-16',
    year: 2010,
    rating: 8.8,
    voteCount: 36240,
    genres: ['Action', 'Sci-Fi', 'Adventure'],
    runtime: 148,
    certification: 'PG-13',
    director: 'Christopher Nolan',
    tagLine: 'Your mind is the scene of the crime.',
    language: 'English',
    trailerYoutubeKey: 'YoHD9XEInc0',
    similarSlugs: ['interstellar', 'the-matrix', 'the-dark-knight'],
    cast: [
      { id: 6193, name: 'Leonardo DiCaprio', character: 'Dom Cobb', profilePath: 'https://image.tmdb.org/t/p/w185/wo2hJpn04vbtmh0B9utCFdsQhxM.jpg' },
      { id: 24045, name: 'Joseph Gordon-Levitt', character: 'Arthur', profilePath: 'https://image.tmdb.org/t/p/w185/dhv9f3A7v2eBfM2Lw5yO2h7Lw3o.jpg' },
      { id: 27578, name: 'Elliot Page', character: 'Ariadne', profilePath: 'https://image.tmdb.org/t/p/w185/tp13UaHXXqS71K170cO66e927m1.jpg' },
      { id: 2524, name: 'Tom Hardy', character: 'Eames', profilePath: 'https://image.tmdb.org/t/p/w185/d8pqFgRBdtQb5ar5oWf3jNn7q8B.jpg' },
      { id: 3895, name: 'Michael Caine', character: 'Miles', profilePath: 'https://image.tmdb.org/t/p/w185/klNxO6j9Y7y3y451W32g7m0v1r2.jpg' },
    ],
  },
  {
    id: 155,
    title: 'The Dark Knight',
    slug: 'the-dark-knight',
    overview:
      'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
    posterPath: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/w1280/oOjJuRwFsQ1eymZf3g2Z72hV3P.jpg',
    releaseDate: '2008-07-18',
    year: 2008,
    rating: 9.0,
    voteCount: 32400,
    genres: ['Action', 'Crime', 'Drama'],
    runtime: 152,
    certification: 'PG-13',
    director: 'Christopher Nolan',
    tagLine: 'Why so serious?',
    language: 'English',
    trailerYoutubeKey: 'EXeTwQWrcwY',
    similarSlugs: ['inception', 'interstellar', 'gladiator-ii'],
    cast: [
      { id: 3894, name: 'Christian Bale', character: 'Bruce Wayne / Batman', profilePath: 'https://image.tmdb.org/t/p/w185/b7fTC9WFuvqNvR1VvJ1Qz8j4j.jpg' },
      { id: 1810, name: 'Heath Ledger', character: 'Joker', profilePath: 'https://image.tmdb.org/t/p/w185/p64TtbZG2UfG51v1i0v6L1L7V4j.jpg' },
      { id: 3895, name: 'Michael Caine', character: 'Alfred Pennyworth', profilePath: 'https://image.tmdb.org/t/p/w185/klNxO6j9Y7y3y451W32g7m0v1r2.jpg' },
      { id: 64, name: 'Gary Oldman', character: 'James Gordon', profilePath: 'https://image.tmdb.org/t/p/w185/2v9FsbtFhJ7PAvYPY59xKuOlQ5L.jpg' },
      { id: 192, name: 'Morgan Freeman', character: 'Lucius Fox', profilePath: 'https://image.tmdb.org/t/p/w185/jPsLqiYGSioBg4Wm4k6wK3V.jpg' },
    ],
  },
  {
    id: 157336,
    title: 'Interstellar',
    slug: 'interstellar',
    overview:
      'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage across deep uncharted cosmos.',
    posterPath: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/w1280/xJHokMbljvjADYdit5fK5VQsXEG.jpg',
    releaseDate: '2014-11-07',
    year: 2014,
    rating: 8.7,
    voteCount: 34100,
    genres: ['Adventure', 'Drama', 'Sci-Fi'],
    runtime: 169,
    certification: 'PG-13',
    director: 'Christopher Nolan',
    tagLine: 'Mankind was born on Earth. It was never meant to die here.',
    language: 'English',
    trailerYoutubeKey: 'zSWdZVtXT7E',
    similarSlugs: ['inception', 'dune-part-two', 'the-matrix'],
    cast: [
      { id: 10297, name: 'Matthew McConaughey', character: 'Cooper', profilePath: 'https://image.tmdb.org/t/p/w185/wDeL9LGrZqVwHqE6U2b0V5D3VqP.jpg' },
      { id: 1813, name: 'Anne Hathaway', character: 'Brand', profilePath: 'https://image.tmdb.org/t/p/w185/tLel4fgQBPikRk40QfB6826c79v.jpg' },
      { id: 83002, name: 'Jessica Chastain', character: 'Murph', profilePath: 'https://image.tmdb.org/t/p/w185/ArJk75WvI2x3G9kR23v0A2.jpg' },
    ],
  },
  {
    id: 693134,
    title: 'Dune: Part Two',
    slug: 'dune-part-two',
    overview:
      'Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, he endeavors to prevent a terrible future only he can foresee.',
    posterPath: 'https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/w1280/xOMo8BRK7PfcJv9JCnx7s520fff.jpg',
    releaseDate: '2024-03-01',
    year: 2024,
    rating: 8.6,
    voteCount: 16200,
    genres: ['Sci-Fi', 'Adventure', 'Action'],
    runtime: 166,
    certification: 'PG-13',
    director: 'Denis Villeneuve',
    tagLine: 'Long live the fighters.',
    language: 'English',
    trailerYoutubeKey: 'Way9Dexny3w',
    similarSlugs: ['interstellar', 'gladiator-ii', 'inception'],
    cast: [
      { id: 1190668, name: 'Timothée Chalamet', character: 'Paul Atreides', profilePath: 'https://image.tmdb.org/t/p/w185/8j5tV2hYl4j00xWk3oVb6L.jpg' },
      { id: 505710, name: 'Zendaya', character: 'Chani', profilePath: 'https://image.tmdb.org/t/p/w185/r3A70N0h6s33G19bL7Xh7h.jpg' },
      { id: 934, name: 'Rebecca Ferguson', character: 'Lady Jessica', profilePath: 'https://image.tmdb.org/t/p/w185/lJloTOheuQNxMRcuX38z.jpg' },
    ],
  },
  {
    id: 872585,
    title: 'Oppenheimer',
    slug: 'oppenheimer',
    overview:
      'The story of J. Robert Oppenheimer\'s role in the development of the atomic bomb during World War II, examining the personal crisis and political consequences of creating humanity\'s ultimate destructive force.',
    posterPath: 'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/w1280/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg',
    releaseDate: '2023-07-21',
    year: 2023,
    rating: 8.9,
    voteCount: 22800,
    genres: ['Drama', 'History', 'Biography'],
    runtime: 180,
    certification: 'R',
    director: 'Christopher Nolan',
    tagLine: 'The world forever changes.',
    language: 'English',
    trailerYoutubeKey: 'uYPbbksJxIg',
    similarSlugs: ['the-dark-knight', 'interstellar'],
    cast: [
      { id: 2037, name: 'Cillian Murphy', character: 'J. Robert Oppenheimer', profilePath: 'https://image.tmdb.org/t/p/w185/360Rjh14rY49B2jGqPj2W.jpg' },
      { id: 5081, name: 'Emily Blunt', character: 'Katherine Oppenheimer', profilePath: 'https://image.tmdb.org/t/p/w185/nPJXaRMguvgB35sW4kH6v.jpg' },
      { id: 3223, name: 'Robert Downey Jr.', character: 'Lewis Strauss', profilePath: 'https://image.tmdb.org/t/p/w185/5qHNjhtjMD4YWH3vi0lZ.jpg' },
    ],
  },
  {
    id: 603,
    title: 'The Matrix',
    slug: 'the-matrix',
    overview:
      'Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the vast and powerful computers who now rule the earth with simulated reality.',
    posterPath: 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/w1280/7u3fh9AR1ouq7Um8756qWdD54X9.jpg',
    releaseDate: '1999-03-31',
    year: 1999,
    rating: 8.7,
    voteCount: 25400,
    genres: ['Action', 'Sci-Fi'],
    runtime: 136,
    certification: 'R',
    director: 'Lilly & Lana Wachowski',
    tagLine: 'Welcome to the Real World.',
    language: 'English',
    trailerYoutubeKey: 'vKQi3bBA1y8',
    similarSlugs: ['inception', 'interstellar'],
    cast: [
      { id: 6384, name: 'Keanu Reeves', character: 'Thomas A. Anderson / Neo', profilePath: 'https://image.tmdb.org/t/p/w185/4D0PpNI0kmP58hgrwGC3wC.jpg' },
      { id: 2975, name: 'Laurence Fishburne', character: 'Morpheus', profilePath: 'https://image.tmdb.org/t/p/w185/8suOhUmPbfKqZujw.jpg' },
      { id: 530, name: 'Carrie-Anne Moss', character: 'Trinity', profilePath: 'https://image.tmdb.org/t/p/w185/87O0g8m.jpg' },
    ],
  },
  {
    id: 558449,
    title: 'Gladiator II',
    slug: 'gladiator-ii',
    overview:
      'Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius must enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist.',
    posterPath: 'https://image.tmdb.org/t/p/w500/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/w1280/euYIwmwkmz95mnXvufEmbL6vavr.jpg',
    releaseDate: '2024-11-22',
    year: 2024,
    rating: 7.8,
    voteCount: 8200,
    genres: ['Action', 'Adventure', 'Drama'],
    runtime: 148,
    certification: 'R',
    director: 'Ridley Scott',
    tagLine: 'Strength and honor reborn.',
    language: 'English',
    trailerYoutubeKey: '4rgYUipGJNo',
    similarSlugs: ['the-dark-knight', 'dune-part-two'],
    cast: [
      { id: 2224997, name: 'Paul Mescal', character: 'Lucius Verus', profilePath: 'https://image.tmdb.org/t/p/w185/mK76F4L.jpg' },
      { id: 1253360, name: 'Pedro Pascal', character: 'Marcus Acacius', profilePath: 'https://image.tmdb.org/t/p/w185/9a1eyW.jpg' },
      { id: 5292, name: 'Denzel Washington', character: 'Macrinus', profilePath: 'https://image.tmdb.org/t/p/w185/jj2.jpg' },
    ],
  },
  {
    id: 129,
    title: 'Spirited Away',
    slug: 'spirited-away',
    overview:
      'A young girl, Chihiro, becomes trapped in a strange world of spirits. After her parents are transformed into giant pigs, she must take a job at a luxurious bathhouse catering to supernatural guests to free them and return to the human realm.',
    posterPath: 'https://image.tmdb.org/t/p/w500/393mhUQRIikJk72qJdEa5nqdhuq.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/w1280/Ab8mkHmkYADjU7wQiOkia99GQI.jpg',
    releaseDate: '2001-07-20',
    year: 2001,
    rating: 8.6,
    voteCount: 16800,
    genres: ['Animation', 'Family', 'Fantasy'],
    runtime: 125,
    certification: 'PG',
    director: 'Hayao Miyazaki',
    tagLine: 'The tunnel led to a mysterious world.',
    language: 'Japanese',
    trailerYoutubeKey: 'ByXuk9QqQkk',
    similarSlugs: ['inception'],
    cast: [
      { id: 19588, name: 'Rumi Hiiragi', character: 'Chihiro Ogino (voice)', profilePath: 'https://image.tmdb.org/t/p/w185/w6Q.jpg' },
      { id: 19589, name: 'Miyu Irino', character: 'Haku (voice)', profilePath: 'https://image.tmdb.org/t/p/w185/4tK.jpg' },
    ],
  },
];

export const CURATED_SERIES: Series[] = [
  {
    id: 1396,
    title: 'Breaking Bad',
    slug: 'breaking-bad',
    overview:
      'Walter White, a New Mexico chemistry teacher, is diagnosed with Stage III cancer and given a prognosis of two years left to live. He chooses to enter the dangerous world of drugs and crime with ex-student Jesse Pinkman to secure his family\'s financial future.',
    posterPath: 'https://image.tmdb.org/t/p/w500/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/w1280/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg',
    firstAirDate: '2008-01-20',
    year: 2008,
    rating: 9.5,
    seasonsCount: 5,
    episodesCount: 62,
    genres: ['Drama', 'Crime', 'Thriller'],
    certification: 'TV-MA',
    creator: 'Vince Gilligan',
    status: 'Ended',
    network: 'AMC',
    trailerYoutubeKey: 'HhesaQXLuRY',
    similarSlugs: ['stranger-things', 'the-last-of-us', 'succession'],
    cast: [
      { id: 17419, name: 'Bryan Cranston', character: 'Walter White', profilePath: 'https://image.tmdb.org/t/p/w185/7Jahy5LZX2Fo4fGJltMreAI49hC.jpg' },
      { id: 84497, name: 'Aaron Paul', character: 'Jesse Pinkman', profilePath: 'https://image.tmdb.org/t/p/w185/u8UdsB9Ki72HgijvuvxY4iL2vO6.jpg' },
      { id: 134531, name: 'Anna Gunn', character: 'Skyler White', profilePath: 'https://image.tmdb.org/t/p/w185/adppcvkXs5sPLa5wH91g0uX7P4x.jpg' },
      { id: 17420, name: 'Dean Norris', character: 'Hank Schrader', profilePath: 'https://image.tmdb.org/t/p/w185/fXyG1q0JkM8d07z8v1g1g0r5z2M.jpg' },
      { id: 23594, name: 'Giancarlo Esposito', character: 'Gustavo Fring', profilePath: 'https://image.tmdb.org/t/p/w185/5F6w8G4V0lV3V6Q6g7Y9P.jpg' },
    ],
  },
  {
    id: 66732,
    title: 'Stranger Things',
    slug: 'stranger-things',
    overview:
      'When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl with telekinetic powers.',
    posterPath: 'https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/w1280/56v2KjBlU4XaOv9rVYEQypROD7P.jpg',
    firstAirDate: '2016-07-15',
    year: 2016,
    rating: 8.7,
    seasonsCount: 4,
    episodesCount: 34,
    genres: ['Sci-Fi', 'Mystery', 'Drama', 'Horror'],
    certification: 'TV-14',
    creator: 'The Duffer Brothers',
    status: 'Returning Series',
    network: 'Netflix',
    trailerYoutubeKey: 'b9EkMc79ZSU',
    similarSlugs: ['breaking-bad', 'the-last-of-us'],
    cast: [
      { id: 1356210, name: 'Millie Bobby Brown', character: 'Eleven', profilePath: 'https://image.tmdb.org/t/p/w185/89q7vV0m6p3k.jpg' },
      { id: 55638, name: 'David Harbour', character: 'Jim Hopper', profilePath: 'https://image.tmdb.org/t/p/w185/chP9mY0t.jpg' },
      { id: 1982, name: 'Winona Ryder', character: 'Joyce Byers', profilePath: 'https://image.tmdb.org/t/p/w185/87O0g8m.jpg' },
    ],
  },
  {
    id: 100088,
    title: 'The Last of Us',
    slug: 'the-last-of-us',
    overview:
      'Twenty years after modern civilization has been destroyed by a fungal pandemic, Joel, a hardened survivor, is hired to smuggle Ellie, a 14-year-old girl, out of an oppressive quarantine zone. What starts as a small job soon becomes a brutal, heartbreaking journey.',
    posterPath: 'https://image.tmdb.org/t/p/w500/uKvVjHNqB5VmOrdxqAt2V7JMrRI.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/w1280/uDgy6hyPd82kOHh6I95FLtLnj6p.jpg',
    firstAirDate: '2023-01-15',
    year: 2023,
    rating: 8.8,
    seasonsCount: 2,
    episodesCount: 16,
    genres: ['Drama', 'Sci-Fi', 'Action'],
    certification: 'TV-MA',
    creator: 'Craig Mazin & Neil Druckmann',
    status: 'Returning Series',
    network: 'HBO',
    trailerYoutubeKey: 'uLtkt8BonwM',
    similarSlugs: ['breaking-bad', 'shogun'],
    cast: [
      { id: 1253360, name: 'Pedro Pascal', character: 'Joel Miller', profilePath: 'https://image.tmdb.org/t/p/w185/9a1eyW.jpg' },
      { id: 2062960, name: 'Bella Ramsey', character: 'Ellie Williams', profilePath: 'https://image.tmdb.org/t/p/w185/77vL90.jpg' },
    ],
  },
  {
    id: 76331,
    title: 'Succession',
    slug: 'succession',
    overview:
      'The Roy family is known for controlling the biggest media and entertainment company in the world. However, their world changes when their aging father steps down from the company, igniting a cutthroat succession war.',
    posterPath: 'https://image.tmdb.org/t/p/w500/7udWdK4K4YlMvI2l5uVbX8u9L3r.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/w1280/etj5CuMu5Bs6973nQf6kI5dE.jpg',
    firstAirDate: '2018-06-03',
    year: 2018,
    rating: 8.9,
    seasonsCount: 4,
    episodesCount: 39,
    genres: ['Drama', 'Business'],
    certification: 'TV-MA',
    creator: 'Jesse Armstrong',
    status: 'Ended',
    network: 'HBO',
    trailerYoutubeKey: 'OzYxJV_rmE8',
    similarSlugs: ['breaking-bad', 'shogun'],
    cast: [
      { id: 11444, name: 'Brian Cox', character: 'Logan Roy', profilePath: 'https://image.tmdb.org/t/p/w185/q47g7g.jpg' },
      { id: 113917, name: 'Jeremy Strong', character: 'Kendall Roy', profilePath: 'https://image.tmdb.org/t/p/w185/7aV1.jpg' },
      { id: 121539, name: 'Sarah Snook', character: 'Shiv Roy', profilePath: 'https://image.tmdb.org/t/p/w185/9x.jpg' },
    ],
  },
  {
    id: 126308,
    title: 'Shōgun',
    slug: 'shogun',
    overview:
      'In feudal Japan in the year 1600, Lord Yoshii Toranaga fights for his life as his enemies on the Council of Regents unite against him, when a mysterious European ship is found marooned in a nearby fishing village.',
    posterPath: 'https://image.tmdb.org/t/p/w500/7O4iVfOMQmdCSxhOg1WnzG1AgYT.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/w1280/v5XyXZ2B99x0P2.jpg',
    firstAirDate: '2024-02-27',
    year: 2024,
    rating: 8.8,
    seasonsCount: 1,
    episodesCount: 10,
    genres: ['Drama', 'History', 'War'],
    certification: 'TV-MA',
    creator: 'Rachel Kondo & Justin Marks',
    status: 'Returning Series',
    network: 'FX / Hulu',
    trailerYoutubeKey: 'yZNHDERaYnU',
    similarSlugs: ['succession', 'the-last-of-us'],
    cast: [
      { id: 11370, name: 'Hiroyuki Sanada', character: 'Lord Yoshii Toranaga', profilePath: 'https://image.tmdb.org/t/p/w185/7N.jpg' },
      { id: 1195610, name: 'Cosmo Jarvis', character: 'John Blackthorne', profilePath: 'https://image.tmdb.org/t/p/w185/4v.jpg' },
      { id: 1989400, name: 'Anna Sawai', character: 'Toda Mariko', profilePath: 'https://image.tmdb.org/t/p/w185/2g.jpg' },
    ],
  },
  {
    id: 114479,
    title: 'The Bear',
    slug: 'the-bear',
    overview:
      'A young fine-dining chef comes home to Chicago to run his family Italian beef sandwich shop after a tragic death. A world away from what he is used to, Carmy must balance the soul-crushing reality of small business ownership and family friction.',
    posterPath: 'https://image.tmdb.org/t/p/w500/690OO9h9P5nB3iFw7e6b0Xk0.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/w1280/m9e1Yw.jpg',
    firstAirDate: '2022-06-23',
    year: 2022,
    rating: 8.7,
    seasonsCount: 3,
    episodesCount: 28,
    genres: ['Comedy', 'Drama'],
    certification: 'TV-MA',
    creator: 'Christopher Storer',
    status: 'Returning Series',
    network: 'FX / Hulu',
    trailerYoutubeKey: 'y-c1a3PzC94',
    similarSlugs: ['succession', 'breaking-bad'],
    cast: [
      { id: 114811, name: 'Jeremy Allen White', character: 'Carmen "Carmy" Berzatto', profilePath: 'https://image.tmdb.org/t/p/w185/r3A.jpg' },
      { id: 147573, name: 'Ebon Moss-Bachrach', character: 'Richard "Richie" Jerimovich', profilePath: 'https://image.tmdb.org/t/p/w185/mB.jpg' },
      { id: 2095655, name: 'Ayo Edebiri', character: 'Sydney Adamu', profilePath: 'https://image.tmdb.org/t/p/w185/aL.jpg' },
    ],
  },
];
