import { LiveChannel } from './types';

export const LIVE_CHANNELS: LiveChannel[] = [
  {
    id: 'ch-1',
    name: 'BBC News HD',
    slug: 'bbc-news-hd',
    number: 101,
    logo: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?w=160&auto=format&fit=crop&q=80',
    category: 'News',
    country: 'United Kingdom',
    countryCode: 'GB',
    language: 'English',
    quality: 'HD',
    epgNow: {
      title: 'BBC World News at 9',
      time: '09:00 - 10:00',
      progress: 65,
    },
    epgNext: {
      title: 'Global Business Report',
      time: '10:00 - 10:30',
    },
  },
  {
    id: 'ch-2',
    name: 'Sky Sports Main Event UHD',
    slug: 'sky-sports-main-event-uhd',
    number: 201,
    logo: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=160&auto=format&fit=crop&q=80',
    category: 'Sports',
    country: 'United Kingdom',
    countryCode: 'GB',
    language: 'English',
    quality: '4K',
    epgNow: {
      title: 'Premier League Matchday Live: Super Sunday',
      time: '14:00 - 17:30',
      progress: 45,
    },
    epgNext: {
      title: 'Match Analysis & Post-Match Reaction',
      time: '17:30 - 18:30',
    },
  },
  {
    id: 'ch-3',
    name: 'ESPN 1 HD',
    slug: 'espn-1-hd',
    number: 202,
    logo: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=160&auto=format&fit=crop&q=80',
    category: 'Sports',
    country: 'United States',
    countryCode: 'US',
    language: 'English',
    quality: 'FHD',
    epgNow: {
      title: 'SportsCenter Live with Scott Van Pelt',
      time: '23:00 - 00:00',
      progress: 30,
    },
    epgNext: {
      title: 'NBA Countdown Live',
      time: '00:00 - 01:00',
    },
  },
  {
    id: 'ch-4',
    name: 'TNT Sports 1 4K Ultimate',
    slug: 'tnt-sports-1-4k-ultimate',
    number: 203,
    logo: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=160&auto=format&fit=crop&q=80',
    category: 'Sports',
    country: 'United Kingdom',
    countryCode: 'GB',
    language: 'English',
    quality: '4K',
    epgNow: {
      title: 'UEFA Champions League Live Tonight',
      time: '19:00 - 22:00',
      progress: 75,
    },
    epgNext: {
      title: 'Champions League Highlights Review',
      time: '22:00 - 23:00',
    },
  },
  {
    id: 'ch-5',
    name: 'CNN International FHD',
    slug: 'cnn-international-fhd',
    number: 102,
    logo: 'https://images.unsplash.com/photo-1495020689067-958852a7765e?w=160&auto=format&fit=crop&q=80',
    category: 'News',
    country: 'United States',
    countryCode: 'US',
    language: 'English',
    quality: 'FHD',
    epgNow: {
      title: 'The Situation Room with Wolf Blitzer',
      time: '18:00 - 19:00',
      progress: 50,
    },
    epgNext: {
      title: 'Anderson Cooper 360',
      time: '19:00 - 20:00',
    },
  },
  {
    id: 'ch-6',
    name: 'HBO Signature HD',
    slug: 'hbo-signature-hd',
    number: 301,
    logo: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=160&auto=format&fit=crop&q=80',
    category: 'Movies',
    country: 'United States',
    countryCode: 'US',
    language: 'English',
    quality: 'HD',
    epgNow: {
      title: 'Blockbuster Showcase: Interstellar',
      time: '20:00 - 22:50',
      progress: 40,
    },
    epgNext: {
      title: 'Inside The Cinema Special Feature',
      time: '22:50 - 23:20',
    },
  },
  {
    id: 'ch-7',
    name: 'National Geographic Wild 4K',
    slug: 'nat-geo-wild-4k',
    number: 401,
    logo: 'https://images.unsplash.com/photo-1534567153574-2b12153a87f0?w=160&auto=format&fit=crop&q=80',
    category: 'Documentary',
    country: 'United States',
    countryCode: 'US',
    language: 'English',
    quality: '4K',
    epgNow: {
      title: 'Predator Oceans: Secrets of the Deep',
      time: '15:00 - 16:00',
      progress: 80,
    },
    epgNext: {
      title: 'Serengeti Migration Chronicles',
      time: '16:00 - 17:00',
    },
  },
  {
    id: 'ch-8',
    name: 'Discovery Channel HD',
    slug: 'discovery-channel-hd',
    number: 402,
    logo: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=160&auto=format&fit=crop&q=80',
    category: 'Documentary',
    country: 'United Kingdom',
    countryCode: 'GB',
    language: 'English',
    quality: 'HD',
    epgNow: {
      title: 'Extreme Engineering: Mega Bridges',
      time: '12:00 - 13:00',
      progress: 25,
    },
    epgNext: {
      title: 'Deadliest Catch New Horizons',
      time: '13:00 - 14:00',
    },
  },
  {
    id: 'ch-9',
    name: 'Cartoon Network FHD',
    slug: 'cartoon-network-fhd',
    number: 501,
    logo: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=160&auto=format&fit=crop&q=80',
    category: 'Kids',
    country: 'United States',
    countryCode: 'US',
    language: 'English',
    quality: 'FHD',
    epgNow: {
      title: 'Adventure Time: Distant Lands',
      time: '16:00 - 16:45',
      progress: 70,
    },
    epgNext: {
      title: 'Teen Titans Go! Marathon',
      time: '16:45 - 17:30',
    },
  },
  {
    id: 'ch-10',
    name: 'Disney Junior HD',
    slug: 'disney-junior-hd',
    number: 502,
    logo: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=160&auto=format&fit=crop&q=80',
    category: 'Kids',
    country: 'United States',
    countryCode: 'US',
    language: 'English',
    quality: 'HD',
    epgNow: {
      title: 'Mickey Mouse Funhouse',
      time: '10:00 - 10:30',
      progress: 50,
    },
    epgNext: {
      title: 'Bluey: Season 3 Special',
      time: '10:30 - 11:00',
    },
  },
  {
    id: 'ch-11',
    name: 'MTV Live 4K',
    slug: 'mtv-live-4k',
    number: 601,
    logo: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=160&auto=format&fit=crop&q=80',
    category: 'Music',
    country: 'United Kingdom',
    countryCode: 'GB',
    language: 'English',
    quality: '4K',
    epgNow: {
      title: 'World Stage: Glastonbury Highlights',
      time: '21:00 - 23:00',
      progress: 60,
    },
    epgNext: {
      title: 'Global Top 20 Hits Non-Stop',
      time: '23:00 - 00:00',
    },
  },
  {
    id: 'ch-12',
    name: 'Canal+ Cinema FHD',
    slug: 'canal-plus-cinema-fhd',
    number: 701,
    logo: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?w=160&auto=format&fit=crop&q=80',
    category: 'International',
    country: 'France',
    countryCode: 'FR',
    language: 'French',
    quality: 'FHD',
    epgNow: {
      title: 'Grand Cinema: Le Festin de Babette',
      time: '20:45 - 22:30',
      progress: 35,
    },
    epgNext: {
      title: 'Les Nouveaux Réalisateurs',
      time: '22:30 - 23:45',
    },
  },
  {
    id: 'ch-13',
    name: 'Sky Cinema Premiere HD',
    slug: 'sky-cinema-premiere-hd',
    number: 302,
    logo: 'https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?w=160&auto=format&fit=crop&q=80',
    category: 'Movies',
    country: 'United Kingdom',
    countryCode: 'GB',
    language: 'English',
    quality: 'HD',
    epgNow: {
      title: 'Premiere Feature: Dune Part Two',
      time: '20:00 - 22:45',
      progress: 20,
    },
    epgNext: {
      title: 'Behind the Scenes & Cast Interviews',
      time: '22:45 - 23:15',
    },
  },
  {
    id: 'ch-14',
    name: 'FOX Sports 1 HD',
    slug: 'fox-sports-1-hd',
    number: 204,
    logo: 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?w=160&auto=format&fit=crop&q=80',
    category: 'Sports',
    country: 'United States',
    countryCode: 'US',
    language: 'English',
    quality: 'HD',
    epgNow: {
      title: 'MLS Matchday Live: Western Conference',
      time: '19:30 - 22:00',
      progress: 55,
    },
    epgNext: {
      title: 'NASCAR Race Hub Express',
      time: '22:00 - 23:00',
    },
  },
  {
    id: 'ch-15',
    name: 'BeIN Sports Premium 1 4K',
    slug: 'bein-sports-premium-1-4k',
    number: 205,
    logo: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=160&auto=format&fit=crop&q=80',
    category: 'Sports',
    country: 'Qatar / Global',
    countryCode: 'QA',
    language: 'Arabic / English',
    quality: '4K',
    epgNow: {
      title: 'La Liga Live: El Clásico Build-up',
      time: '19:00 - 21:00',
      progress: 40,
    },
    epgNext: {
      title: 'La Liga Special Presentation',
      time: '21:00 - 23:30',
    },
  },
  {
    id: 'ch-16',
    name: 'Eurosport 1 4K',
    slug: 'eurosport-1-4k',
    number: 206,
    logo: 'https://images.unsplash.com/photo-1517649763962-0c623266ddc0?w=160&auto=format&fit=crop&q=80',
    category: 'Sports',
    country: 'Germany / Europe',
    countryCode: 'DE',
    language: 'English',
    quality: '4K',
    epgNow: {
      title: 'Grand Tour Cycling: Stage 18 Live',
      time: '13:00 - 17:30',
      progress: 70,
    },
    epgNext: {
      title: 'The Breakaway Post-Stage Debrief',
      time: '17:30 - 18:30',
    },
  },
];
